title: "Oh Sunday"
description: "去走走吧"
baseurl: ""
url: "https://username.github.io"

plugins:
  - jekyll-paginate
  - jekyll-feed

permalink: /:title/
highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
  extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
